# Generated by Django 5.0.6 on 2026-06-10 21:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0002_initial'),
        ('documentos', '0001_initial'),
        ('empresas', '0001_initial'),
        ('produccion', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_costo', models.CharField(choices=[('material', 'Material'), ('mano_obra', 'Mano de Obra'), ('servicio_externo', 'Servicio Externo'), ('transporte', 'Transporte'), ('embalaje', 'Embalaje'), ('instalacion', 'Instalación'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='produccion.ordenproduccion')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'costos_orden',
            },
        ),
        migrations.CreateModel(
            name='IngresoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('abono', 'Abono'), ('pago_total', 'Pago Total'), ('anticipo', 'Anticipo'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metodo_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.documento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='produccion.ordenproduccion')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingresos_orden',
            },
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('defecto_material', 'Defecto de Material'), ('error_proceso', 'Error de Proceso'), ('dano_transporte', 'Daño en Transporte'), ('rechazo_cliente', 'Rechazo de Cliente'), ('otro', 'Otro')], max_length=20)),
                ('gravedad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('costo_asociado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('accion_correctiva', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='registrada', max_length=20)),
                ('evidencia_imagen', models.ImageField(blank=True, null=True, upload_to='no_conformidades/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.etapaproduccion')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.lotematerial')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.material')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.ordenproduccion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades_registradas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'no_conformidades',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
