# Generated by Django 5.0.6 on 2026-06-10 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('icono', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'estados_cliente',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True)),
                ('avance_visible', models.PositiveIntegerField(default=0, help_text='0-100%')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('imagen_publica', models.ImageField(blank=True, null=True, upload_to='seguimiento_cliente/')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estado_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_cliente.estadocliente')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_cliente', to='produccion.ordenproduccion')),
            ],
            options={
                'db_table': 'seguimiento_cliente',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
