# Generated by Django 5.0.6 on 2026-06-10 21:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciada', 'Iniciada'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('saltada', 'Saltada')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('evidencia_imagen', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.etapaproduccion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orden_etapas',
                'ordering': ['etapa__orden'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=30, unique=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_termino_real', models.DateTimeField(blank=True, null=True)),
                ('estado_general', models.CharField(choices=[('pedido_recibido', 'Pedido Recibido'), ('materiales_pendientes', 'Materiales Pendientes'), ('materiales_preparados', 'Materiales Preparados'), ('en_produccion', 'En Producción'), ('en_terminaciones', 'En Terminaciones'), ('control_calidad', 'Control de Calidad'), ('listo_despacho', 'Listo para Despacho'), ('despachado', 'Despachado'), ('instalado', 'Instalado / Entregado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='pedido_recibido', max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('avance_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('codigo_seguimiento', models.CharField(blank=True, max_length=20, unique=True)),
                ('token_cliente', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('costo_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('utilidad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='empresas.empresa')),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.etapaproduccion')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'db_table': 'ordenes_produccion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenMaterialReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reservada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.lotematerial')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.material')),
                ('reservado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_reservados', to='produccion.ordenproduccion')),
            ],
            options={
                'db_table': 'orden_materiales_reservados',
            },
        ),
        migrations.CreateModel(
            name='OrdenMaterialConsumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('merma', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.ordenetapa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.lotematerial')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.material')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_consumidos', to='produccion.ordenproduccion')),
            ],
            options={
                'db_table': 'orden_materiales_consumidos',
            },
        ),
        migrations.AddField(
            model_name='ordenetapa',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_orden', to='produccion.ordenproduccion'),
        ),
        migrations.CreateModel(
            name='HistorialEstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('etapa_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.etapaproduccion')),
                ('etapa_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.etapaproduccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='produccion.ordenproduccion')),
            ],
            options={
                'db_table': 'historial_estado_orden',
                'ordering': ['-fecha'],
            },
        ),
    ]
