# Generated by Django 5.0.6 on 2026-06-10 21:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'categorias_producto',
            },
        ),
        migrations.CreateModel(
            name='EtapaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible_cliente', models.BooleanField(default=False)),
                ('estado_cliente_equivalente', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'etapas_produccion',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_venta_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoriaproducto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('obligatorio', models.BooleanField(default=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.etapaproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_producto', to='productos.producto')),
            ],
            options={
                'db_table': 'producto_etapas',
                'ordering': ['orden'],
                'unique_together': {('producto', 'etapa')},
            },
        ),
        migrations.CreateModel(
            name='ProductoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('merma_estimada_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('observacion', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.material')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_bom', to='productos.producto')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.unidadmedida')),
            ],
            options={
                'db_table': 'producto_materiales',
                'unique_together': {('producto', 'material')},
            },
        ),
    ]
